const fs = require('fs-extra')
if (fs.existsSync('.env')) require('dotenv').config({ path: __dirname+'/.env' })


//═══════[Required Variables]════════\\
global.audio= "" ;  
global.video= "" ;
global.port =process.env.PORT
global.appUrl=process.env.APP_URL || ""                       // put your app url here,
global.email ="saimsamsun789@gmail.com"
global.location="Lahore,Pakistan."


global.mongodb= process.env.MONGODB_URI || "mongodb+srv://kenebiobi2:gTtB5bWsgtzKAVma@bots.iurrqsb.mongodb.net/?retryWrites=true&w=majority&appName=bots"
global.allowJids= process.env.ALLOW_JID || "null" 
global.blockJids= process.env.BLOCK_JID || "null"
global.DATABASE_URL = process.env.DATABASE_URL || "postgresql://suhail_db_user:ICrqH7aVTnjhyWGUHV9Xy7M7D2uvHAZk@dpg-cq3pob4s1f4s73fjthkg-a.oregon-postgres.render.com/suhail_db"

global.timezone= process.env.TZ || process.env.TIME_ZONE || "WAT";
global.github=process.env.GITHUB|| "https://github.com/SuhailTechInfo/Suhail-Md";
global.gurl  =process.env.GURL  || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643";
global.website=process.env.GURL || "https://whatsapp.com/channel/0029Va9thusJP20yWxQ6N643" ; 
global.THUMB_IMAGE = process.env.THUMB_IMAGE || process.env.IMAGE || "https://github.com/SuhailTechInfo/Suhail-Md/blob/main/lib/assets/suhail.jpg?raw=true" ; // SET LOGO FOR IMAGE 
global.caption = process.env.CAPTION || global.caption || "ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ" 


global.devs = "923184474176" // Developer Contact
global.sudo = process.env.SUDO ? process.env.SUDO.replace(/[\s+]/g, '') : "2349018909938";
global.owner= process.env.OWNER_NUMBER ? process.env.OWNER_NUMBER.replace(/[\s+]/g, '') : "2349018909938";




//========================= [ BOT SETTINGS ] ======8===================\\
global.style = process.env.STYLE   || Math.floor(Math.random()*6) || '0'  // put '1' to "5" here to check bot styles
global.flush = process.env.FLUSH   || "false"; // Make it "true" if bot not responed
global.gdbye = process.env.GOODBYE || process.env.CAN_GOODBYE || "false"; 
global.wlcm  = process.env.WELCOME || process.env.CAN_WELCOME || "false";  // Make it "false" for disable WELCOME 

global.warncount = process.env.WARN_COUNT || 2
global.disablepm = process.env.DISABLE_PM || "false"
global.disablegroup = process.env.DISABLE_GROUPS || "false", // disable bot in groups when public mode

global.MsgsInLog = process.env.MSGS_IN_LOG|| "false" // "true"  to see messages , "log" to show logs , "false" to hide logs messages
global.userImages= process.env.USER_IMAGES || "text" // "text" // set Image/video urls here
global.waPresence= process.env.WAPRESENCE ||  "unavailable" ; // 'unavailable' | 'available' | 'composing' | 'recording' | 'paused'


//========================= [ AUTO READ MSGS & CMDS ] =========================\\
global.readcmds = process.env.READ_COMMAND || "false"
global.readmessage = process.env.READ_MESSAGE || "false"
global.readmessagefrom = process.env.READ_MESSAGE_FROM || "null,923xxxxxxxx";


//========================= [ AUTO SAVE & READ STATUS ] =========================\\
global.read_status = process.env.AUTO_READ_STATUS || "false"
global.save_status = process.env.AUTO_SAVE_STATUS || "false"
global.save_status_from =  process.env.SAVE_STATUS_FROM  || "null,923xxxxxxxx";
global.read_status_from =  process.env.READ_STATUS_FROM  ||  "923184474176,923xxxxxxxx";

global.api_smd = "https://api-smd.onrender.com" //  || "https://api-smd-1.vercel.app" // expires
global.scan = "https://suhail-md-vtsf.onrender.com";


global.SESSION_ID = process.env.SESSION_ID ||  "SUHAIL_14_52_07_08_ewogICJjcmVkcy5qc29uIjogIntcbiAgXCJub2lzZUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTEyLFxuICAgICAgICA0OCxcbiAgICAgICAgMTU0LFxuICAgICAgICAxOTAsXG4gICAgICAgIDExMSxcbiAgICAgICAgNDMsXG4gICAgICAgIDExMSxcbiAgICAgICAgNjksXG4gICAgICAgIDQ0LFxuICAgICAgICAyMixcbiAgICAgICAgMTU5LFxuICAgICAgICAxNjMsXG4gICAgICAgIDExMixcbiAgICAgICAgMTQ5LFxuICAgICAgICAyLFxuICAgICAgICAzOCxcbiAgICAgICAgMjEwLFxuICAgICAgICAyNDUsXG4gICAgICAgIDQ2LFxuICAgICAgICA5MSxcbiAgICAgICAgNDEsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjE5LFxuICAgICAgICAxMjAsXG4gICAgICAgIDAsXG4gICAgICAgIDIwMSxcbiAgICAgICAgMTQ5LFxuICAgICAgICA3NCxcbiAgICAgICAgNTEsXG4gICAgICAgIDQ4LFxuICAgICAgICAxMTAsXG4gICAgICAgIDExNlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAxNzAsXG4gICAgICAgIDI0MyxcbiAgICAgICAgNzUsXG4gICAgICAgIDI0MyxcbiAgICAgICAgMzgsXG4gICAgICAgIDE3NixcbiAgICAgICAgOTgsXG4gICAgICAgIDIxMyxcbiAgICAgICAgMTg3LFxuICAgICAgICAyMTMsXG4gICAgICAgIDIxMSxcbiAgICAgICAgMTk5LFxuICAgICAgICAxNjgsXG4gICAgICAgIDY3LFxuICAgICAgICAxNzMsXG4gICAgICAgIDE0NixcbiAgICAgICAgMTc5LFxuICAgICAgICAxMDYsXG4gICAgICAgIDE5NCxcbiAgICAgICAgMTIwLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE0MSxcbiAgICAgICAgNDIsXG4gICAgICAgIDIyOCxcbiAgICAgICAgODUsXG4gICAgICAgIDksXG4gICAgICAgIDI1MCxcbiAgICAgICAgOTEsXG4gICAgICAgIDIxNSxcbiAgICAgICAgNzIsXG4gICAgICAgIDEyLFxuICAgICAgICA3NFxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJwYWlyaW5nRXBoZW1lcmFsS2V5UGFpclwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI4LFxuICAgICAgICAyNDIsXG4gICAgICAgIDE3MSxcbiAgICAgICAgODYsXG4gICAgICAgIDI0MixcbiAgICAgICAgNzEsXG4gICAgICAgIDI0MixcbiAgICAgICAgOTQsXG4gICAgICAgIDQ3LFxuICAgICAgICAyMDEsXG4gICAgICAgIDIyMyxcbiAgICAgICAgMTE0LFxuICAgICAgICAyMjEsXG4gICAgICAgIDI3LFxuICAgICAgICA1OCxcbiAgICAgICAgNDcsXG4gICAgICAgIDIzNixcbiAgICAgICAgOTQsXG4gICAgICAgIDIzMSxcbiAgICAgICAgMjQ2LFxuICAgICAgICAyMDMsXG4gICAgICAgIDI0MCxcbiAgICAgICAgMTAxLFxuICAgICAgICAxODQsXG4gICAgICAgIDE2NCxcbiAgICAgICAgOTQsXG4gICAgICAgIDI5LFxuICAgICAgICA2MixcbiAgICAgICAgNTMsXG4gICAgICAgIDEyNixcbiAgICAgICAgMTk2LFxuICAgICAgICA3OVxuICAgICAgXVxuICAgIH0sXG4gICAgXCJwdWJsaWNcIjoge1xuICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICBcImRhdGFcIjogW1xuICAgICAgICAyNSxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMDksXG4gICAgICAgIDE5MyxcbiAgICAgICAgMjAsXG4gICAgICAgIDE1MixcbiAgICAgICAgNCxcbiAgICAgICAgMTM1LFxuICAgICAgICAyNDgsXG4gICAgICAgIDIyNCxcbiAgICAgICAgMjAsXG4gICAgICAgIDIyNSxcbiAgICAgICAgOTcsXG4gICAgICAgIDI2LFxuICAgICAgICAxMjMsXG4gICAgICAgIDIzNixcbiAgICAgICAgNDMsXG4gICAgICAgIDEyMCxcbiAgICAgICAgNTUsXG4gICAgICAgIDksXG4gICAgICAgIDcxLFxuICAgICAgICAxNTUsXG4gICAgICAgIDM0LFxuICAgICAgICAxMjQsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTA1LFxuICAgICAgICAyNixcbiAgICAgICAgNjgsXG4gICAgICAgIDEzNyxcbiAgICAgICAgMTU0LFxuICAgICAgICAzNCxcbiAgICAgICAgNlxuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRJZGVudGl0eUtleVwiOiB7XG4gICAgXCJwcml2YXRlXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgNTYsXG4gICAgICAgIDc3LFxuICAgICAgICAxNDUsXG4gICAgICAgIDE1NixcbiAgICAgICAgMjIzLFxuICAgICAgICA3NCxcbiAgICAgICAgNDAsXG4gICAgICAgIDEzMyxcbiAgICAgICAgMjAwLFxuICAgICAgICAyMTEsXG4gICAgICAgIDEzNSxcbiAgICAgICAgMTE2LFxuICAgICAgICA2MCxcbiAgICAgICAgNjYsXG4gICAgICAgIDE2NyxcbiAgICAgICAgMTEyLFxuICAgICAgICAyNixcbiAgICAgICAgMyxcbiAgICAgICAgMTA3LFxuICAgICAgICAxNTMsXG4gICAgICAgIDIzMyxcbiAgICAgICAgNDAsXG4gICAgICAgIDE3NSxcbiAgICAgICAgNCxcbiAgICAgICAgMjQ0LFxuICAgICAgICAxMjAsXG4gICAgICAgIDIyNSxcbiAgICAgICAgNDQsXG4gICAgICAgIDY5LFxuICAgICAgICAxMDQsXG4gICAgICAgIDIzLFxuICAgICAgICAxMTZcbiAgICAgIF1cbiAgICB9LFxuICAgIFwicHVibGljXCI6IHtcbiAgICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgMTI1LFxuICAgICAgICAxNzAsXG4gICAgICAgIDQ1LFxuICAgICAgICAxMzEsXG4gICAgICAgIDEyMSxcbiAgICAgICAgMTc3LFxuICAgICAgICA2OSxcbiAgICAgICAgMjM4LFxuICAgICAgICAzNCxcbiAgICAgICAgOTgsXG4gICAgICAgIDQsXG4gICAgICAgIDIwOCxcbiAgICAgICAgNzgsXG4gICAgICAgIDEwLFxuICAgICAgICAyOCxcbiAgICAgICAgMjI4LFxuICAgICAgICAyNSxcbiAgICAgICAgNjMsXG4gICAgICAgIDEwLFxuICAgICAgICAyMTgsXG4gICAgICAgIDcxLFxuICAgICAgICAxMTEsXG4gICAgICAgIDQ3LFxuICAgICAgICAxNDcsXG4gICAgICAgIDI1MixcbiAgICAgICAgMTc4LFxuICAgICAgICA5MyxcbiAgICAgICAgMTQwLFxuICAgICAgICAyNTEsXG4gICAgICAgIDEyMixcbiAgICAgICAgMjQ5LFxuICAgICAgICA1N1xuICAgICAgXVxuICAgIH1cbiAgfSxcbiAgXCJzaWduZWRQcmVLZXlcIjoge1xuICAgIFwia2V5UGFpclwiOiB7XG4gICAgICBcInByaXZhdGVcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICAwLFxuICAgICAgICAgIDE2NSxcbiAgICAgICAgICAxNDIsXG4gICAgICAgICAgMTU5LFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAzOCxcbiAgICAgICAgICAyMjcsXG4gICAgICAgICAgMTMwLFxuICAgICAgICAgIDE4MyxcbiAgICAgICAgICAyMjUsXG4gICAgICAgICAgOTgsXG4gICAgICAgICAgMjA1LFxuICAgICAgICAgIDI3LFxuICAgICAgICAgIDg4LFxuICAgICAgICAgIDI0MixcbiAgICAgICAgICAxOTYsXG4gICAgICAgICAgMjQ3LFxuICAgICAgICAgIDEzMyxcbiAgICAgICAgICAxNDMsXG4gICAgICAgICAgMTk4LFxuICAgICAgICAgIDYxLFxuICAgICAgICAgIDIxMCxcbiAgICAgICAgICA4MixcbiAgICAgICAgICAxNzksXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgMjIwLFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAyMDAsXG4gICAgICAgICAgMTE4LFxuICAgICAgICAgIDE5NyxcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxMTdcbiAgICAgICAgXVxuICAgICAgfSxcbiAgICAgIFwicHVibGljXCI6IHtcbiAgICAgICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgICAgMjE4LFxuICAgICAgICAgIDEzNyxcbiAgICAgICAgICAxNDEsXG4gICAgICAgICAgMTI1LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDk2LFxuICAgICAgICAgIDE5NCxcbiAgICAgICAgICAxODgsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDExNCxcbiAgICAgICAgICAxMjYsXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgNCxcbiAgICAgICAgICAxNzYsXG4gICAgICAgICAgOTksXG4gICAgICAgICAgMjM4LFxuICAgICAgICAgIDIzMCxcbiAgICAgICAgICAyMDksXG4gICAgICAgICAgNDMsXG4gICAgICAgICAgOTcsXG4gICAgICAgICAgMTcyLFxuICAgICAgICAgIDIyNCxcbiAgICAgICAgICAxMzIsXG4gICAgICAgICAgMTcsXG4gICAgICAgICAgMTc5LFxuICAgICAgICAgIDEzOCxcbiAgICAgICAgICA4NCxcbiAgICAgICAgICA4OCxcbiAgICAgICAgICAyMzYsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDE0NSxcbiAgICAgICAgICA0OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfSxcbiAgICBcInNpZ25hdHVyZVwiOiB7XG4gICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgIFwiZGF0YVwiOiBbXG4gICAgICAgIDE1NSxcbiAgICAgICAgMTM2LFxuICAgICAgICAxMixcbiAgICAgICAgMjA3LFxuICAgICAgICAyNCxcbiAgICAgICAgMTc4LFxuICAgICAgICAyMjYsXG4gICAgICAgIDE4NixcbiAgICAgICAgMjEzLFxuICAgICAgICAyMzUsXG4gICAgICAgIDExOCxcbiAgICAgICAgNTAsXG4gICAgICAgIDEyLFxuICAgICAgICAyMDYsXG4gICAgICAgIDEyNSxcbiAgICAgICAgMjExLFxuICAgICAgICAzNixcbiAgICAgICAgNyxcbiAgICAgICAgMjE0LFxuICAgICAgICA0MCxcbiAgICAgICAgMTUxLFxuICAgICAgICAxMDIsXG4gICAgICAgIDU5LFxuICAgICAgICA0NCxcbiAgICAgICAgMjIxLFxuICAgICAgICAxNzIsXG4gICAgICAgIDIyMixcbiAgICAgICAgMjMsXG4gICAgICAgIDE0OSxcbiAgICAgICAgMTAzLFxuICAgICAgICAyNSxcbiAgICAgICAgMTM2LFxuICAgICAgICA3NyxcbiAgICAgICAgMTk3LFxuICAgICAgICA5MCxcbiAgICAgICAgMjQ3LFxuICAgICAgICA5NyxcbiAgICAgICAgMjA4LFxuICAgICAgICA5NSxcbiAgICAgICAgOTgsXG4gICAgICAgIDI2LFxuICAgICAgICAyMDMsXG4gICAgICAgIDE0MyxcbiAgICAgICAgMTEzLFxuICAgICAgICA2LFxuICAgICAgICAxMDIsXG4gICAgICAgIDcsXG4gICAgICAgIDc3LFxuICAgICAgICAxMzIsXG4gICAgICAgIDI1MyxcbiAgICAgICAgMTgsXG4gICAgICAgIDEyOSxcbiAgICAgICAgMjMzLFxuICAgICAgICAxOTEsXG4gICAgICAgIDE0LFxuICAgICAgICAxODYsXG4gICAgICAgIDIzNixcbiAgICAgICAgNDIsXG4gICAgICAgIDEzMSxcbiAgICAgICAgMTI4LFxuICAgICAgICAxNjksXG4gICAgICAgIDI1LFxuICAgICAgICAxMjMsXG4gICAgICAgIDEzMlxuICAgICAgXVxuICAgIH0sXG4gICAgXCJrZXlJZFwiOiAxXG4gIH0sXG4gIFwicmVnaXN0cmF0aW9uSWRcIjogMjUyLFxuICBcImFkdlNlY3JldEtleVwiOiBcInBxNXVwWmN3bC96bXE4eFVOYWV5NmZkUi9nSWc1NHlLQjR2QVNvWDQ3Zkk9XCIsXG4gIFwicHJvY2Vzc2VkSGlzdG9yeU1lc3NhZ2VzXCI6IFtdLFxuICBcIm5leHRQcmVLZXlJZFwiOiAzMSxcbiAgXCJmaXJzdFVudXBsb2FkZWRQcmVLZXlJZFwiOiAzMSxcbiAgXCJhY2NvdW50U3luY0NvdW50ZXJcIjogMCxcbiAgXCJhY2NvdW50U2V0dGluZ3NcIjoge1xuICAgIFwidW5hcmNoaXZlQ2hhdHNcIjogZmFsc2VcbiAgfSxcbiAgXCJkZXZpY2VJZFwiOiBcImprWjRQV2syUU9LVFpHMnA5dWg2NndcIixcbiAgXCJwaG9uZUlkXCI6IFwiYWE5N2RhYTItNjc5My00YjQ5LWI1MzQtZDVkZjllY2E4MThjXCIsXG4gIFwiaWRlbnRpdHlJZFwiOiB7XG4gICAgXCJ0eXBlXCI6IFwiQnVmZmVyXCIsXG4gICAgXCJkYXRhXCI6IFtcbiAgICAgIDExNixcbiAgICAgIDIzNixcbiAgICAgIDE3MSxcbiAgICAgIDIxMSxcbiAgICAgIDc5LFxuICAgICAgMTg3LFxuICAgICAgMixcbiAgICAgIDc5LFxuICAgICAgMjA0LFxuICAgICAgMjM0LFxuICAgICAgMzIsXG4gICAgICAyMDIsXG4gICAgICAxODMsXG4gICAgICAyMTIsXG4gICAgICAxNTAsXG4gICAgICA3MSxcbiAgICAgIDE1NixcbiAgICAgIDIxMyxcbiAgICAgIDEwNSxcbiAgICAgIDcwXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdGVyZWRcIjogZmFsc2UsXG4gIFwiYmFja3VwVG9rZW5cIjoge1xuICAgIFwidHlwZVwiOiBcIkJ1ZmZlclwiLFxuICAgIFwiZGF0YVwiOiBbXG4gICAgICA1OCxcbiAgICAgIDIxNyxcbiAgICAgIDIzMCxcbiAgICAgIDQxLFxuICAgICAgMTMsXG4gICAgICAyNDUsXG4gICAgICAyNDUsXG4gICAgICA4MSxcbiAgICAgIDg2LFxuICAgICAgNzcsXG4gICAgICAxNjUsXG4gICAgICA1OCxcbiAgICAgIDYsXG4gICAgICA2OSxcbiAgICAgIDEzNCxcbiAgICAgIDIzNyxcbiAgICAgIDg4LFxuICAgICAgMTMyLFxuICAgICAgMTkwLFxuICAgICAgMjMxXG4gICAgXVxuICB9LFxuICBcInJlZ2lzdHJhdGlvblwiOiB7fSxcbiAgXCJhY2NvdW50XCI6IHtcbiAgICBcImRldGFpbHNcIjogXCJDTjdiKzVzQ0VLejZyN1FHR0FNZ0FDZ0FcIixcbiAgICBcImFjY291bnRTaWduYXR1cmVLZXlcIjogXCJKWmlWbkV5WkQ4TXM0QmZqNUszRThVMXQ0bHhQRHBvWlVKbmJKT1IzNHpFPVwiLFxuICAgIFwiYWNjb3VudFNpZ25hdHVyZVwiOiBcIml1bEZOQzErL0dXRElTQ0dxU0Q0c3pDRk1lN2dkVGlna2JlMHJ4NThOVG5yQlNXN1JDQjhrbnVYVWNpK2x1NFNYSS9CNkZMQUhkb0wyN2dHYXlLcEJ3PT1cIixcbiAgICBcImRldmljZVNpZ25hdHVyZVwiOiBcIlBBZ1VZeWt1WVlVNWVmamZsY1VKbzIyd1IrNzFNUHBVM1E4RkJDYmVJQjcyb2tLWTZTSDYrRlVTeEdnbHNJWGV2dGxkWlR5dXVRZUpMdjRGTngvNmlnPT1cIlxuICB9LFxuICBcIm1lXCI6IHtcbiAgICBcImlkXCI6IFwiMjM0NzAyNTgyMjU2NTo3QHMud2hhdHNhcHAubmV0XCIsXG4gICAgXCJsaWRcIjogXCIxNzEwMjE1Mzc2NTI5ODc6N0BsaWRcIlxuICB9LFxuICBcInNpZ25hbElkZW50aXRpZXNcIjogW1xuICAgIHtcbiAgICAgIFwiaWRlbnRpZmllclwiOiB7XG4gICAgICAgIFwibmFtZVwiOiBcIjIzNDcwMjU4MjI1NjU6N0BzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDM3LFxuICAgICAgICAgIDE1MixcbiAgICAgICAgICAxNDksXG4gICAgICAgICAgMTU2LFxuICAgICAgICAgIDc2LFxuICAgICAgICAgIDE1MyxcbiAgICAgICAgICAxNSxcbiAgICAgICAgICAxOTUsXG4gICAgICAgICAgNDQsXG4gICAgICAgICAgMjI0LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTczLFxuICAgICAgICAgIDE5NixcbiAgICAgICAgICAyNDEsXG4gICAgICAgICAgNzcsXG4gICAgICAgICAgMTA5LFxuICAgICAgICAgIDIyNixcbiAgICAgICAgICA5MixcbiAgICAgICAgICA3OSxcbiAgICAgICAgICAxNCxcbiAgICAgICAgICAxNTQsXG4gICAgICAgICAgMjUsXG4gICAgICAgICAgODAsXG4gICAgICAgICAgMTUzLFxuICAgICAgICAgIDIxOSxcbiAgICAgICAgICAzNixcbiAgICAgICAgICAyMjgsXG4gICAgICAgICAgMTE5LFxuICAgICAgICAgIDIyNyxcbiAgICAgICAgICA0OVxuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwNDUwMzUyLFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBT2RxXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFPZHEuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxK2ROTGU1T1NDOHZ3TjlFSUJqMXkrb2R1TW9LZzV3eTZtQU15TFd2VkpzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjU5NTUyMDk5MCxcImN1cnJlbnRJbmRleFwiOjEsXCJkZXZpY2VJbmRleGVzXCI6WzAsMV19LFwidGltZXN0YW1wXCI6XCIwXCJ9Igp9+GCps65IETOscqLzrnUgyDwn5iP8J+YjlwiXG4gIH0sXG4gIFwic2lnbmFsSWRlbnRpdGllc1wiOiBbXG4gICAge1xuICAgICAgXCJpZGVudGlmaWVyXCI6IHtcbiAgICAgICAgXCJuYW1lXCI6IFwiMjM0OTAxODkwOTkzODo0OUBzLndoYXRzYXBwLm5ldFwiLFxuICAgICAgICBcImRldmljZUlkXCI6IDBcbiAgICAgIH0sXG4gICAgICBcImlkZW50aWZpZXJLZXlcIjoge1xuICAgICAgICBcInR5cGVcIjogXCJCdWZmZXJcIixcbiAgICAgICAgXCJkYXRhXCI6IFtcbiAgICAgICAgICA1LFxuICAgICAgICAgIDU5LFxuICAgICAgICAgIDE2NyxcbiAgICAgICAgICA5NyxcbiAgICAgICAgICAyMTgsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAxOTEsXG4gICAgICAgICAgNDAsXG4gICAgICAgICAgOTYsXG4gICAgICAgICAgNDgsXG4gICAgICAgICAgMjAzLFxuICAgICAgICAgIDkxLFxuICAgICAgICAgIDIxNyxcbiAgICAgICAgICAyMzUsXG4gICAgICAgICAgMTMsXG4gICAgICAgICAgMSxcbiAgICAgICAgICAyMjksXG4gICAgICAgICAgMjM3LFxuICAgICAgICAgIDIzLFxuICAgICAgICAgIDE5MyxcbiAgICAgICAgICAyMSxcbiAgICAgICAgICAyNTQsXG4gICAgICAgICAgOTEsXG4gICAgICAgICAgMTAyLFxuICAgICAgICAgIDIzMSxcbiAgICAgICAgICAzOSxcbiAgICAgICAgICAxNzIsXG4gICAgICAgICAgMTIyLFxuICAgICAgICAgIDQwLFxuICAgICAgICAgIDEwMSxcbiAgICAgICAgICA2MyxcbiAgICAgICAgICA1NCxcbiAgICAgICAgICA4M1xuICAgICAgICBdXG4gICAgICB9XG4gICAgfVxuICBdLFxuICBcInBsYXRmb3JtXCI6IFwiYW5kcm9pZFwiLFxuICBcImxhc3RBY2NvdW50U3luY1RpbWVzdGFtcFwiOiAxNzIwMzU4ODY0LFxuICBcIm15QXBwU3RhdGVLZXlJZFwiOiBcIkFBQUFBS0dZXCJcbn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLR1MuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJCWHFzdWJndDhYazQvcTNuY2NsQ2podjZ2ZS8xYnE4NVNOUzUyMWpxMXlzPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyNzY5OTM5MDMsXCJjdXJyZW50SW5kZXhcIjoxLFwiZGV2aWNlSW5kZXhlc1wiOlswLDFdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtHVC5qc29uIjogIntcImtleURhdGFcIjpcInBXb21kcWo1Qi9KeXMvWEsvako2cnR4THRHS2hYWm52RnFzblB2NnFKaVU9XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTI3Njk5MzkwMyxcImN1cnJlbnRJbmRleFwiOjIsXCJkZXZpY2VJbmRleGVzXCI6WzAsMl19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0dVLmpzb24iOiAie1wia2V5RGF0YVwiOlwiZGx3MXBLZHRiK3AxUW5zNFFxY3diRUpNSGZSZk56SFV3bktIUmdna01BST1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjc2OTkzOTAzLFwiY3VycmVudEluZGV4XCI6MyxcImRldmljZUluZGV4ZXNcIjpbMCwyXX0sXCJ0aW1lc3RhbXBcIjpcIjBcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLR1YuanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCIxK3FmeHVCRTI1SmtvU3lyYjRLd25sWXl5cVRNK2NjbTNRZStick1XN01jPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyNzY5OTM5MDMsXCJjdXJyZW50SW5kZXhcIjo0LFwiZGV2aWNlSW5kZXhlc1wiOlswLDJdfSxcInRpbWVzdGFtcFwiOlwiMFwifSIsCiAgImFwcC1zdGF0ZS1zeW5jLWtleS1BQUFBQUtHVy5qc29uIjogIntcImtleURhdGFcIjpcIjZUc21kQmd1WVhsVEZjbVprbFRNQ2xBeXdZZ3FhU3h4aGdEZzZPNXVvMU09XCIsXCJmaW5nZXJwcmludFwiOntcInJhd0lkXCI6MTI3Njk5MzkwMyxcImN1cnJlbnRJbmRleFwiOjYsXCJkZXZpY2VJbmRleGVzXCI6WzAsMiw1XX0sXCJ0aW1lc3RhbXBcIjpcIjE3MjAzNTgyMzYzMjZcIn0iLAogICJhcHAtc3RhdGUtc3luYy1rZXktQUFBQUFLR1guanNvbiI6ICJ7XCJrZXlEYXRhXCI6XCJGVWVuVmVWRzhZSGlHNlI3dWR0SUg5bWk2MDFWYjNad0RiWWhBSnNHdjFNPVwiLFwiZmluZ2VycHJpbnRcIjp7XCJyYXdJZFwiOjEyNzY5OTM5MDMsXCJjdXJyZW50SW5kZXhcIjo3LFwiZGV2aWNlSW5kZXhlc1wiOlswLDIsNV19LFwidGltZXN0YW1wXCI6XCIwXCJ9IiwKICAiYXBwLXN0YXRlLXN5bmMta2V5LUFBQUFBS0dZLmpzb24iOiAie1wia2V5RGF0YVwiOlwiWi9tbW5lQnE2V1hSdXd3OENKaE5IamE5Y2VPbXJqSGFMYkdNTHI2M2l3MD1cIixcImZpbmdlcnByaW50XCI6e1wicmF3SWRcIjoxMjc2OTkzOTAzLFwiY3VycmVudEluZGV4XCI6OCxcImRldmljZUluZGV4ZXNcIjpbMCwyLDVdfSxcInRpbWVzdGFtcFwiOlwiMTcyMDM1ODg1MzUwNVwifSIKfQ=="  // PUT your SESSION_ID 


module.exports = {

  menu: process.env.MENU || "A17_Md", /**  Available @MENU @Schemes 1: Aztec_Md, 2: A17_Md, 3: Suhail-Md Default ---------- If Not Choose then it Randomely Pic One Of Them Each time **/

  HANDLERS: process.env.PREFIX  || "*",
  BRANCH  : process.env.BRANCH  || "main",
  VERSION : process.env.VERSION || "1.3.8",
  caption : global.caption || "" , // ```『 ᴘᴏᴡᴇʀᴇᴅ ʙʏ sᴜʜᴀɪʟ²²¹-ᴍᴅ 』```", //*『sᴜʙsᴄʀɪʙᴇ • sᴜʜᴀɪʟ ᴛᴇᴄʜ』*\n youtube.com/@suhailtechinfo0"),
 
  author : process.env.PACK_AUTHER|| "Obi David 😏😎",
  packname: process.env.PACK_NAME || "Davis 😉",
  botname : process.env.BOT_NAME  || "Davis 😉",
  ownername:process.env.OWNER_NAME|| "Obi David 😏😎",


  errorChat : process.env.ERROR_CHAT || "",
  KOYEB_API : process.env.KOYEB_API  || "false",

  REMOVE_BG_KEY : process.env.REMOVE_BG_KEY  || "B4chCTUbqkYVGAu2RxmJc6A7",
  OPENAI_API_KEY: process.env.OPENAI_API_KEY || "sk-proj-OIbqZQuG1gI6D2iiyjoLT3BlbkFJV1KogkiU2mt3P0M731Hq",
  HEROKU_API_KEY: process.env.HEROKU_API_KEY || "",
  HEROKU_APP_NAME:process.env.HEROKU_APP_NAME|| "",
  antilink_values:process.env.ANTILINK_VALUES|| "all",
  HEROKU: process.env.HEROKU_APP_NAME && process.env.HEROKU_API_KEY,


  WORKTYPE: process.env.WORKTYPE || process.env.MODE|| "public",
  LANG: ( process.env.THEME ||  "SUHAIL"  ).toUpperCase(),



};



global.ELEVENLAB_API_KEY = process.env.ELEVENLAB_API_KEY || "e5a9cf5650b3cc169345ee96bd5267d8";
global.aitts_Voice_Id = process.env.AITTS_ID|| "37";





















global.rank = "updated"
global.isMongodb = false; 
let file = require.resolve(__filename)
fs.watchFile(file, () => { fs.unwatchFile(file);console.log(`Update'${__filename}'`);delete require.cache[file];	require(file); })
 

// ========================= [ Disables in V.1.2.8 ] ===============================\\  
  //style : process.env.STYLE || "2",  // put '1' & "2" here to check bot styles
  //readmessage:process.env.READ_MESSAGE|| "false",
  //warncount: process.env.WARN_COUNT || 3,
  //userImages:process.env.USER_IMAGES|| "text",  // SET IMAGE AND VIDEO URL FOR BOT MENUS 
  //disablepm: process.env.DISABLE_PM || "false",
  //MsgsInLog: process.env.MSGS_IN_LOG|| "false", // "true"  to see messages , "log" to open logs , "false" to hide logs messages
  //readcmds:process.env.READ_COMMANDS|| "false", 
  //alwaysonline:process.env.WAPRESENCE|| "unavailable", // 'unavailable' | 'online' | 'composing' | 'recording' | 'paused'
  //read_status: process.env.AUTO_READ_STATUS || "false",
  //save_status: process.env.AUTO_SAVE_STATUS || "false",
  //aitts_Voice_Id : process.env.AITTS_ID || "37",
  //ELEVENLAB_API_KEY: process.env.ELEVENLAB_API_KEY  || "",
