name: Deploy to Koyeb

on:
  push:
    branches:
      - main  # or any branch you want to deploy from

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t my-suhail-md .

      - name: Tag Docker image
        run: docker tag my-suhail-md ${{ secrets.DOCKER_USERNAME }}/my-suhail-md:latest

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/my-suhail-md:latest

      - name: Deploy to Koyeb
        run: |
          curl -X POST \
            https://app.koyeb.com/v1/apps/YOUR_APP_ID/deployments \
            -H "Authorization: Bearer ${{ secrets.KOYEB_API_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{
              "spec": {
                "containers": [
                  {
                    "image": "${{ secrets.DOCKER_USERNAME }}/my-suhail-md:latest"
                  }
                ]
              }
            }'
